import { Product, Farmer, Order } from "../types";

export const mockFarmer: Farmer = {
  id: "1",
  name: "John Adebayo",
  email: "john.adebayo@email.com",
  phone: "08012345678",
  userType: "farmer",
  location: "Ikenne Central",
  ward: "Ward 1 - Ikenne Central",
  isVerified: true,
  createdAt: new Date("2024-01-15"),
  farmName: "Adebayo Farms",
  farmSize: 5.5,
  primaryCrop: "Rubber",
  rating: 4.8,
  totalSales: 450000,
};

export const mockProducts: Product[] = [
  {
    id: "1",
    farmerId: "1",
    farmerName: "John Adebayo",
    title: "Fresh Rubber Latex",
    description:
      "Premium quality rubber latex tapped fresh this morning. High yield variety with excellent quality.",
    category: "rubber",
    price: 800,
    unit: "kg",
    availableQuantity: 500,
    minimumOrder: 10,
    location: "Ikenne Central",
    ward: "Ward 1",
    images: ["/image-rubber.png"],
    rating: 4.8,
    reviewCount: 12,
    isActive: true,
    createdAt: new Date("2024-11-01"),
  },
  {
    id: "2",
    farmerId: "2",
    farmerName: "Mary Ogundimu",
    title: "Premium Cassava Flour",
    description:
      "Freshly processed cassava flour, perfect for baking and cooking. Made from high-quality cassava roots.",
    category: "cassava",
    price: 350,
    unit: "kg",
    availableQuantity: 200,
    minimumOrder: 5,
    location: "Ilisan",
    ward: "Ward 2",
    images: ["/image-flour.png"],
    rating: 4.6,
    reviewCount: 8,
    isActive: true,
    createdAt: new Date("2024-11-02"),
  },
  {
    id: "3",
    farmerId: "3",
    farmerName: "Paul Oladele",
    title: "Fresh Yam Tubers",
    description:
      "Large, fresh yam tubers harvested this week. Perfect for household consumption or resale.",
    category: "yam",
    price: 500,
    unit: "piece",
    availableQuantity: 100,
    minimumOrder: 2,
    location: "Ikenne North",
    ward: "Ward 3",
    images: ["/image-yam.jpg"],
    rating: 4.9,
    reviewCount: 15,
    isActive: true,
    createdAt: new Date("2024-10-28"),
  },
];

export const mockOrders: Order[] = [
  {
    id: "1",
    buyerId: "1",
    farmerId: "1",
    productId: "1",
    quantity: 50,
    totalAmount: 40000,
    status: "processing",
    deliveryAddress: "Lagos Road, Ikenne",
    orderDate: new Date("2024-11-05"),
    deliveryDate: new Date("2024-11-07"),
  },
  {
    id: "2",
    buyerId: "1",
    farmerId: "2",
    productId: "2",
    quantity: 25,
    totalAmount: 8750,
    status: "delivered",
    deliveryAddress: "Lagos Road, Ikenne",
    orderDate: new Date("2024-10-30"),
    deliveryDate: new Date("2024-11-01"),
  },
];
